[package]
name = "sample_graphql_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
async-graphql = "5"
async-graphql-actix-web = "5"
serde = { version = "1.0", features = ["derive"] }
